### PR TITLE
Align scrolling behavior across perspectives #LMR-1942

### PR DESCRIPTION
**Pull request by livthomas**

### CODE REVIEW

**Comment by livthomas** [comment]
If you mean the event listeners then probably no. I have tried it several times before but the event is not emitted when you listen directly to the DOM events. It's probably some special jQuery thing.

**Comment by kubedo8** [comment]
I mean something like this https://valor-software.com/ngx-bootstrap/#/alerts

**Comment by livthomas** [comment]
Ok, I'll try to switch it to `ngx-bootstrap` to avoid using jQuery.

**Comment by livthomas** [comment]
@kubedo8 Done.

**Pull request merged**
